### PR TITLE
Check for both src and dst when copying full box

### PR DESCRIPTION
**Pull request by canbal**

### CODE REVIEW

**Comment by dwbuiten** [comment]
Can you elaborate a bit on the cause/fix this commit addresses? It's not immediately clear to me what implications this will have — I'm not so familiar with this part of the code.

**Comment by canbal** [comment]
We are randomly corrupting inputs and feeding to l-smash to fix security issues. This particular change was to avoid a crash that was happening when the `dst` was not allocated as a `fullbox` but we were invoking `isom_fullbox_common_copy`

**Comment by dwbuiten** [comment]
Gotcha.

I don't think I am qualified enough in this bit to know if this fix is correct, or if there is a different fix (to allocate the proper struct, or if the copy call is incorrect in the first place).

**Comment by canbal** [comment]
I see your point. I'm not familiar with the codebase to that extent. I was just trying to mitigate the crash we were seeing and this fix worked fine.

**Comment by VFR-maniac** [comment]
I want to know what causes such improper allocation for fullbox.
I can't accept this commit since the values of version and flags fields of src are filled by reading stream and dst shall take the values from src if it is fullbox.
If I accepted this commit, you can't dump actual values in streams in such undesirable case.

**Comment by canbal** [comment]
This fix is from our early days of testing for security issues. I tried to look through our logs but I can't find the exact input file that led us to this fix. At the time we were using v1.0.0, so there's a fair chance that this might not be an issue at this point. I'm closing this until (and if) I can find another case where this causes a problem.

**Pull request closed without merging**
