### PR TITLE
[RFC] Add I/O error checking for start code searches

### PR DESCRIPTION
**Pull request by dwbuiten**
I'm not sure if the new API and error code is the best way or not. Comments welcome.

### CODE REVIEW

**Comment by VFR-maniac** [comment]
Globally, looks fine for me.

I guess there are existing nameless errors which could be assigned to LSMASH_ERR_IO.
It's ideal you replace with if existing. :)

**Comment by dwbuiten** [comment]
Sure.

Do you want me to add such commits to this pull request, or shall this be merged first?

**Comment by VFR-maniac** [comment]
OK. I'll merge this first. Anyway thanks.

**Comment by jeeb** [comment]
Closing as the patches have been merged.

**Pull request closed without merging**
