### PR TITLE
Fix 1-byte extra read when file is qt compatible

### PR DESCRIPTION
**Pull request by canbal**

### CODE REVIEW

**Comment by dwbuiten** [comment]
Looks reasonable, I think. Was this caught and/or verified with valgrind or a similar tool?

**Comment by canbal** [comment]
Yes, this was caught via valgrind.

Can

**Comment by dwbuiten** [comment]
@VFR-maniac I think this is OK to merge, then.

**Comment by VFR-maniac** [comment]
Hmm, the patch is OK.

During reading the codes, I noticed there is an existing edge case which loses the last one character when qt_compatible == 1 and hdlr->componentName_length == 256.

Let's say the file is a quicktime file format (qt_compatible == 1) and the first byte of hdlr->componentName is 255 and then the length of the pascal string is 256.
```
length = LSMASH_MIN( 255, hdlr->componentName_length );
```
so, length is now 255.
From hdlr->componentName[1] to hdlr->componentName[255] is a valid block, therefore, this 255 byte block should be copied to the handler_name_shadow. But your patch copies length - file->qt_compatible i.e. 254 bytes. This is undesirable.
I'll fix this.

**Comment by VFR-maniac** [comment]
Applied: 76a2493
Thank you.

**Pull request closed without merging**
